- hosts: servers
  sudo: yes
  tasks:
    - name: install python 
      yum: name=python state=installed
    
    - name: set firewall
      shell: lokkit -s http -s ssh


    - name: ensure open JDK 1.8 is latest version
      yum: name=java-1.8.0-openjdk state=latest

    - name: install jenkins repository
      get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

    - name: add jenkins repository
      rpm_key: key=http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
      
    - name: ensure jenkins at the latest version
      yum: name=jenkins state=latest 

    - name: ensure jenkins is running and enabled
      service: name=jenkins state=running enabled=yes 

    - name: update iptable for jenkins
      shell: lokkit -p 8080:tcp


    - name: download jenkins cli tool
      get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/tmp

    - name: install plugin 
      action: command java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 install-plugin {{ item }}
      with_items:
        - build-pipeline-plugin
        - git
        - github
        - github-api

    - name: add jenkins to root group
      command: gpasswd -a jenkins root

    - name: add read right of /etc/shadow to root group
      command: chmod g+r /etc/shadow
    
    - name: set JENKINS_USER to jenkins 
      lineinfile: dest=/etc/sysconfig/jenkins 
                  regexp="^JENKINS_USER"
                  line="JENKINS_USER=jenkins"

    - name: set JENKINS_PORT to 8080 
      lineinfile: dest=/etc/sysconfig/jenkins 
                  regexp="^JENKINS_PORT"
                  line="JENKINS_PORT=8080"

    - name: jenkins restart 
      action: command java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 safe-restart 
