- hosts: servers
  sudo: yes
  tasks:
    - name: install epel-release first
      yum: name=epel-release state=latest

    - name: install node
      yum: name=nodejs state=latest
     
    - name: install npm
      yum: name=npm state=latest enablerepo=epel
